### ISSUE TITLE
Pivot values error

### ISSUE THREAD

**Issue by ghost** [citiususc/stac#3]
I am using the code you developed for STAC. Using the results coming from the friedman test, I get the following error when trying to run the
holm_multitest:
Traceback (most recent call last):

   File "<ipython-input-202-d7caa7a0c14d>", line 1, in <module>
     runfile('/home/prubbens/Desktop/Datasets/In Silico Communities/dettests.py', wdir='/home/prubbens/Desktop/Datasets/In
Silico Communities')

   File
"/home/prubbens/anaconda3/lib/python3.4/site-packages/spyder/utils/site/sitecustomize.py",
line 866, in runfile
     execfile(filename, namespace)

   File
"/home/prubbens/anaconda3/lib/python3.4/site-packages/spyder/utils/site/sitecustomize.py",
line 102, in execfile
     exec(compile(f.read(), filename, 'exec'), namespace)

   File "/home/prubbens/Desktop/Datasets/In Silico Communities/dettests.py", line 92, in <module>
     comp, z, p, adj_p = holm_multitest(pivots)

   File "/home/prubbens/Desktop/Datasets/In Silico Communities/nonparametric_tests.py", line 520, in holm_multitest
     p_values, z_values, comparisons = map(list, zip(*sorted(zip(p_values, z_values, comparisons), key=lambda t: t[0])))

ValueError: need more than 0 values to unpack

Inspecting the holm_multitest() function, I see that comparisons is an empty list. Which argument should I give to holm_multitest()? I am now giving it pivots, coming from the friedman test.

**Comment by ghost** [comment]
I've been able to solve it, using this [answer ](http://stackoverflow.com/questions/17322668/typeerror-dict-keys-object-does-not-support-indexing) and proper formatting pivots as a dictionary.
